version: "3"
services:
  proxy:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - nusaraya
    volumes:
      - ./www:/var/www
  php73:
    build:
      context: .
      dockerfile: php73/Dockerfile
    container_name: php73
    working_dir: /var/www
    networks:
      - nusaraya
    volumes:
      - ./www:/var/www
  php74:
    build:
      context: .
      dockerfile: php74/Dockerfile
    container_name: php74
    working_dir: /var/www
    networks:
      - nusaraya
    volumes:
      - ./www:/var/www
  bpmdb:
    image: postgres:11-alpine
    container_name: bpmdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./opt:/opt
  citradb:
    image: postgres:9-alpine
    container_name: citradb
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./citradata:/var/lib/postgresql/data
      - ./opt:/opt
networks:
  nusaraya:
    driver: bridge
