version: "3"
services:
  app:
    image: nusaraya/bpm:latest
    container_name: bpm
    restart: unless-stopped
    working_dir: /var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8888:8888
    volumes:
      - ./www:/var/www
  db:
    image: postgres:11-alpine
    container_name: bpmdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./opt:/opt
  # adminer:
  #   image: adminer
  #   container_name: bpmadminer
  #   restart: always
  #   ports:
  #     - 8080:8080
